#pragma once

const int
    RTC_WDT_BASE = 0x600B1C00,
    RTC_WDT_CONFIG0_REG = RTC_WDT_BASE + 0x0000,
    RTC_WDT_SWD_CONFIG_REG = RTC_WDT_BASE + 0x001C,

    RTC_WDT_FLASHBOOT_MOD_EN = 12,
    RTC_WDT_SWD_AUTO_FEED_EN = 18;
