#!/usr/bin/env sh
set -e
cd $(dirname "$0")

mkdir -p tmp

riscv64-unknown-elf-gcc \
  -march=rv32imac_zicsr -mabi=ilp32 -nostdlib \
  -fno-ident \
  -Oz -g \
  -T probe.ld \
  -Wl,--gc-sections,--no-warn-rwx-segments \
  -o tmp/probe.elf probe.c

riscv64-unknown-elf-objdump \
  -d -l -S \
  -s -j .text -j .srodata -j .data \
  tmp/probe.elf > tmp/probe.elf.S
